title: GJBBANG
description: Welcome to my little corner of the internet <br /> — a tech blog where I jot down things I’ve learned, stuff I’m figuring out, and random thoughts along the way. <br /> It’s kind of like a personal dev diary. <br /> Not everything is polished, but it’s real, and it’s mine.
author: GIJIN BANG
avatar: /logo.JPG
email: kzo12341@gmail.com
location: in Seoul, Korea

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================

logo: logo.JPG
social:
  name: GIJIN BANG
  links:
    - https://github.com/GJBBang
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
